name: Scheduled Health Check

on:
  workflow_dispatch:    # manual run
  schedule:             # scheduled run
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh
