name: Scheduled Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main

permissions:
  contents: write   # <- add this

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # <- important to allow push
      - name: Run health check
        run: bash ./health-check.sh
